name: Action Practice


on:
  push:
  schedule:
   - cron: "0 14 * * *"
  

env:
  TZ: Asia/Shanghai

jobs:
  # a single job
  a-job-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          pip3 install requests beautifulsoup4 lxml asyncio aiohttp nest_asyncio cryptography pycryptodome argparse telethon
      - name: Run
        env:         
         STRING: ${{ secrets.STRING }}
         TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
         CHANNEL_USERNAME: ${{ secrets.CHANNEL_USERNAME }}
         TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
         
         
        run: TELEGRAM_API_ID=$TELEGRAM_API_ID TELEGRAM_API_HASH=$TELEGRAM_API_HASH CHANNEL_USERNAME=$CHANNEL_USERNAME STRING=$STRING python3 ./run.py --encode_code ${{ secrets.PASSWORD }}

   #   - name: Run2
    #    run: |
   #       python3 ./image.py --encode_code ${{ secrets.PASSWORD }}
      - name: Commit
        env:
          GIT_NAME: GitHub Actions[Bot]
          GIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        
        run: |
          git config --local user.name $GIT_NAME
          git config --local user.email $GIT_EMAIL
          git pull
           
          
          git reset --mixed origin/main
          git add .
          git commit -m "Github action update at `date '+%Y-%m-%d %H:%M:%S'`."
          git push
